#dynamic_padding = true
live_config_reload = true
#"window.opacity" = 1.0

[[colors.indexed_colors]]
color = "#F5A97F"
index = 16

[[colors.indexed_colors]]
color = "#F4DBD6"
index = 17

[colors.bright]
black = "#5B6078"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#ED8796"
white = "#A5ADCB"
yellow = "#EED49F"

[colors.cursor]
cursor = "#F4DBD6"
text = "#24273A"

[colors.dim]
black = "#494D64"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#ED8796"
white = "#B8C0E0"
yellow = "#EED49F"

[colors.hints.end]
background = "#A5ADCB"
foreground = "#24273A"

[colors.hints.start]
background = "#EED49F"
foreground = "#24273A"

[colors.normal]
black = "#494D64"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#ED8796"
white = "#B8C0E0"
yellow = "#EED49F"

[colors.primary]
background = "#24273A"
bright_foreground = "#CAD3F5"
dim_foreground = "#CAD3F5"
foreground = "#CAD3F5"

[colors.search.focused_match]
background = "#A6DA95"
foreground = "#24273A"

#[colors.search.footer_bar]
#background = "#A5ADCB"
#foreground = "#24273A"

[colors.search.matches]
background = "#A5ADCB"
foreground = "#24273A"

[colors.selection]
background = "#F4DBD6"
text = "#24273A"

[colors.vi_mode_cursor]
cursor = "#B7BDF8"
text = "#24273A"

[font]
size = 12

[font.normal]
family = "JetbrainsMonoNL"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[shell]
program = "/bin/fish"

[window.padding]
x = 20
y = 20
